repository_type: pipeline
nf_core_version: "4.1.0"
template:
  author: Alexander Peltzer, Gregor Sturm, Julian Schwab
  description: A pipeline to produce provenance reports.
  force: false
  is_nfcore: true
  name: provenancereport
  org: nf-core
  outdir: .
  version: 1.0.0dev
lint:
  files_exist:
    - assets/multiqc_config.yml
    - .github/workflows/linting_comment.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  multiqc_config: false
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - .github/PULL_REQUEST_TEMPLATE.md
